name: example
description: A new Flutter project.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cloud_firestore: ^6.0.2
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutterfire_gen_annotation:
    path: ../../flutterfire_gen_annotation
  flutterfire_gen_utils:
    path: ../../flutterfire_gen_utils
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  flutterfire_gen:
    path: ../
  test: ^1.21.0
